version: 2

general:
    artifacts:
        - /home/ubuntu/JnABatteryOptimiser/app/build/outputs/apk/

machine:
    java:
        version: oraclejdk8
    environment:
        ANDROID_HOME: /usr/local/android-sdk-linux

dependencies:
    pre:
        - chmod +x gradlew
    override:
        - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-26.0.2,android-25,extra-google-m2repository,extra-google-google_play_services,extra-android-support
        - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies

test:
    override:
        - (./gradlew assemble):
            timeout: 360